### ISSUE TITLE
pytorch接口的dataset_loader迭代报错

### ISSUE THREAD

**Issue by YWonchall** [chenjie04/Learning_the_COCO#2]
```
dataDir = './mscoco_2017/val2017'
annFile = './mscoco_2017/annotations/instances_val2017.json'
coco = COCO(annFile)
dataset = CocoDetection(root=dataDir,annFile=annFile)

dataset_loader = torch.utils.data.DataLoader(dataset=dataset,
                                           batch_size=4, 
                                           shuffle=True,
                                           collate_fn=dataset.collate_fn)
for batch_index,(features, target) in  enumerate(dataset_loader):
    print(batch_index)
```

对于上述代码，迭代过程中会不定时报错
```
File "/workspace/coco_dataset.py", line 86, in __getitem__
    x1 = (bboxes[:, 1])
IndexError: too many indices for tensor of dimension 1
```
如果方便的话辛苦帮忙看一下呀，谢谢！

**Comment by chenjie04** [comment]
抱歉！我是初学者，我不会啊，那是我的学习笔记







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenjie04/Learning_the_COCO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 下午5:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenjie04/Learning_the_COCO] pytorch接口的dataset_loader迭代报错 (Issue #2)





 dataDir = './mscoco_2017/val2017' annFile = './mscoco_2017/annotations/instances_val2017.json' coco = COCO(annFile) dataset = CocoDetection(root=dataDir,annFile=annFile) dataset_loader = torch.utils.data.DataLoader(dataset=dataset,                                            batch_size=4,                                             shuffle=True,                                            collate_fn=dataset.collate_fn) for batch_index,(features, target) in  enumerate(dataset_loader):     print(batch_index)  
对于上述代码，迭代过程中会不定时报错
 File "/workspace/coco_dataset.py", line 86, in __getitem__     x1 = (bboxes[:, 1]) IndexError: too many indices for tensor of dimension 1  
如果方便的话辛苦帮忙看一下呀，谢谢！

**Comment by BeiYazi0** [comment]
这个报错说明 bboxes 纬度小于2，大概率 bboxes 是空列表，那么 anns = coco.loadAnns(annids) 返回值为 []

**Comment by chenjie04** [comment]
> 这个报错说明 bboxes 纬度小于2，大概率 bboxes 是空列表，那么 anns = coco.loadAnns(annids) 返回值为 []

是嘞，时隔两年了，我也才搞明白COCO数据集里面有些图像是没有目标的，所以anns返回值为空。在mmdetection框架的实现中，有一个参数 filter_empty_gt=True 可以把空图片过滤掉。
